export const SET_DATALIST = "SET_DATALIST";
export const SET_CURRENT_PAGE_NUMBER = "SET_CURRENT_PAGE_NUMBER";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
export const SET_CURRENT_PAGE_DATA = "SET_CURRENT_PAGE_DATA";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const RESET_STATE = "RESET_STATE";
